### PR TITLE
Compiling in Windows and Vector3f Functionality

### PR DESCRIPTION
**Pull request by waredavid**
...e in Visual Studio (I am still having problems getting TBB linked right which is why it is not building) Also includes additional fuctionality in the Vector3f class for addition, subtraction, scalar multiplication and scalar division, cross product, and dot product.

### CODE REVIEW

**Comment by tehul** [comment]
>50 files changed.

It looks like you cloned an updated version of the project here, but replaced all the up-to-date files with old files somehow. I'm getting a lot of compiler errors for code that was fixed awhile back. Maybe this happened from running `git clone` in the same folder twice? I can't really tell. 

You should try reverting to the last commit and making your changes again, making sure to only change the files you need to.

**Comment by tehul** [comment]
Also, it looks like you changed the name of `vector3` to `vector3f`. Perhaps the original name was an accident, but a lot of code calls `vector3` right now, so all that would need to be refactored as well.

**Comment by tehul** [comment]
I sent your repo a [pull request](https://github.com/waredavid/CS5500/pull/1) to fix some of these things. Check it out.

**Comment by waredavid** [comment]
I never changed the name of Vector3 me and my partner wrote the Vector3f file in our first section of the project someone else has gotten ride of it and changed the file structure significantly.  These file structure changes did not come to the repository on my computer When I pulled. . . I will be more careful about the file structure in the future.

**Comment by tehul** [comment]
Ah, duly noted. Maybe some mishap happened. All's good though, just get that Vector3f back into shape (and maybe CMakeLists.txt) and you should be good.

**Pull request closed without merging**
